#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"

ENVFILE="$HERE/usr/share/ocdesktop/hermes.env"
export OCDESKTOP_HERMES_URL="${OCDESKTOP_HERMES_URL:-ws://vmi3137202.lobster-bonytongue.ts.net:8770/ocdesktop}"
export OCDESKTOP_HERMES_ENV="${OCDESKTOP_HERMES_ENV:-$ENVFILE}"

exec "$HERE/usr/bin/ocdesktop" "$@"
